<?php
/*
 * Superb_Recommend
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Superb
 * @package    Superb_Recommend
 * @author     Superb <hello@wearesuperb.com>
 * @copyright  Copyright (c) 2015 Superb Media Limited
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<style type="text/css">
    /* Reset the .std styles */
    .std ul.products-grid li {
        list-style: none;
        margin-left: 0;
    }
    .std ul.products-grid li .product-info {
        padding-bottom: 0 !important;
        min-height: 0 !important;
    }
    .widget-new-products h2 {
        text-align: center;
    }
</style>
<div class="main-container col1-layout">
    <div class="main">
        <div class="col-main">
            <?php echo $this->getChildHtml(); ?>
        </div>
    </div>
</div>
