<?php
/*
 * Superb_Recommend
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Superb
 * @package    Superb_Recommend
 * @author     Superb <hello@wearesuperb.com>
 * @copyright  Copyright (c) 2015 Superb Media Limited
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php $helper = Mage::helper('superbrecommend'); ?>
<script type="text/javascript">
//<![CDATA[
    (function(){
    var tracker = document.createElement('script'); tracker.type = 'text/javascript'; tracker.async = true;tracker.src = <?php echo json_encode($helper->getApiJsUrl());?>;
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(tracker, s);
    })();
    var _taq = _taq || [];
    _taq.push(["setAccountId", <?php echo json_encode($helper->getAccountId());?>] ,["setTrackerUrl",<?php echo json_encode($helper->getApiUrl());?>], ["setCurrentCurrencyCode",<?php echo json_encode(Mage::app()->getStore()->getCurrentCurrencyCode());?>], ["setCurrentStoreCode",<?php echo json_encode(Mage::app()->getStore()->getCode());?>]);
    <?php $data = $this->getTrackingData();?>
    <?php if (is_array($data)):?><?php foreach ($data as $record): if (is_array($record) && count($record)):?>
    _taq.push(<?php echo json_encode($record);?>);
    <?php endif; endforeach; endif; ?>
//]]>
</script>
<?php echo $this->getChildHtml('recommend_tracker'); echo $this->getChildHtml('recommend_tracker_cart'); ?>
<script type="text/javascript">
//<![CDATA[
    _taq.push(["trackPageview"]);
//]]>
</script>
